baseURL = "https://chaojie.fun/"
languageCode = "en-us"
title = "Chaojie's Homeâœï¸"
theme = "cactus"
rss = true


[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 2

[[menu.main]]
name = "Articles"
url = "/posts"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[menu.main]]
name = "About"
url = "/about"
weight = 5

[params]
  description = """
  Hi, I'm chaojie([æ½®æˆ’](/about/)). I'm working at [Douban](https://en.wikipedia.org/wiki/Douban) as Python engineer.

  I'm interested in programming, movies, design and some hardware stuffs. Sometimes have unrealistic fantasies.

  I have a dogğŸ¶ named [Ï€](https://pai.dog/).

  â€œæ„¿ä½ è‡ªå·±æœ‰å……åˆ†çš„å¿è€å»æ‹…å½“ï¼Œæœ‰å……åˆ†å•çº¯çš„å¿ƒå»ä¿¡ä»°ã€‚â€ ------ é‡Œå°”å…‹

  """
  mainSectionTitle = "Articles"
  mainSection = "posts"
  showAllPostsOnHomePage = false
  postsOnHomePage = 6
  mathjax = true
  rss = true
  showAllPostsArchive = true
  googleAnalytics = "G-XDREGKCZH0"

[[params.social]]
  name = "github"
  link = "https://github.com/ischaojie"

[[params.social]]
  name = "douban"
  link = "https://douban.com/people/218724191"

[[params.social]]
  name = "twitter"
  link = "https://twitter.com/chaojie_cn"

[[params.social]]
  name = "email"
  link = "hi@chaojie.fun"

[params.comments]
  enabled = true
  engine = "giscus"
  [params.comments.utterances]
    repo = "ischaojie/blog"
    label = "comments"
    theme = "github-light"
    IssueTerm = "title"
  [params.comments.giscus]
    repo = "ischaojie/blog"
    repoId = "MDEwOlJlcG9zaXRvcnkyODk4MDA1NTY="
    category = "Announcements"
    categoryId = "DIC_kwDOEUYBbM4CPWbs"
    theme = "light"
    mapping = "title"

